<?php

namespace AppBundle\Repository;

/**
 * AttributeKeyValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributeKeyValueRepository extends \Doctrine\ORM\EntityRepository
{
}
