<?php

namespace AppBundle\Repository;

/**
 * AttributeKeyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributeKeyRepository extends \Doctrine\ORM\EntityRepository
{
}
