<?php

namespace AppBundle\Repository;

/**
 * DocumentAttributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentAttributeRepository extends \Doctrine\ORM\EntityRepository
{
}
