attributekeyvalue_index:
    path:     /
    defaults: { _controller: "AppBundle:AttributeKeyValue:index" }
    methods:  GET

attributekeyvalue_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:AttributeKeyValue:show" }
    methods:  GET

attributekeyvalue_new:
    path:     /new
    defaults: { _controller: "AppBundle:AttributeKeyValue:new" }
    methods:  [GET, POST]

attributekeyvalue_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:AttributeKeyValue:edit" }
    methods:  [GET, POST]

attributekeyvalue_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:AttributeKeyValue:delete" }
    methods:  DELETE
