doc_index:
    path:     /
    defaults: { _controller: "AppBundle:Document:index" }
    methods:  GET

doc_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Document:show" }
    methods:  GET

doc_new:
    path:     /new
    defaults: { _controller: "AppBundle:Document:new" }
    methods:  [GET, POST]

doc_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Document:edit" }
    methods:  [GET, POST]

doc_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Document:delete" }
    methods:  [DELETE, GET]
