app_doc:
    resource: "@AppBundle/Resources/config/routing/document.yml"
    prefix:   /
    
app_file:
    resource: "@AppBundle/Resources/config/routing/file.yml"
    prefix:   /file
    
app_search:
    resource: "@AppBundle/Resources/config/routing/search.yml"
    prefix:   /search

